### ISSUE TITLE
When saving, "page not found" returned.

### ISSUE THREAD

**Issue by hlfshell** [themeskult/wp-svbtle#1]
Hitting save on an idea returns "Page not found". I suspect it might have to do with the fact that I use "nice"-ified post-title URLs for my posts?

**Comment by rickyrauch** [comment]
I can't reproduce this error. Can you provide more details? Thanks

**Comment by hlfshell** [comment]
Sure thing! Sorry about the short description - I was suddenly slammed with work.
I just ran through a couple of scenarios and am trying to recreate it. Close my ticket until I can make a proper recreate map.
