### ISSUE TITLE
Nested Comments Unreadable

### ISSUE THREAD

**Issue by edent** [themeskult/wp-svbtle#100]
After comments are nested more than 3 deep, they become unreadable.  Because they are indented and have a limited width (500px) they often end up looking like

`th
is
is an
exa
mple`

I've changed https://github.com/gravityonmars/wp-svbtle/blob/master/wp-content/themes/svbtle/style.css#L55

to

```
ol.commentlist{list-style:none; margin:0; padding: 0; max-width: 100%; }
```

So that nested comments take up the full width of the window.

Thoughts?

**Comment by edent** [comment]
Thanks :-)

**Comment by ahmetb** [comment]
Ricardo, how are you maintaining patches to the style.css when a new version of Svbtle comes out and you need to copy their style.css file? Will all these CSS patches be gone?

**Comment by rickyrauch** [comment]
Nop, I change stuff that it's not in svbtle stylesheet mostly.

**Comment by jmergy** [comment]
Just played latest code and it fixed my issues on nested as well. Thanks!
