### ISSUE TITLE
Wordpress MU support

### ISSUE THREAD

**Issue by ijafri** [themeskult/wp-svbtle#103]
Does it support wordpress MU? If it doesn't do you have a plan to support it, because then it would make it a perfect blogging network like subvtle for users like me, for example i want to allow other members in my specific community to use it. Also a homepage which features the latest posts from the network. Thanks!

**Comment by jmergy** [comment]
I'm running wp-svbtle in an MU setup.

**Comment by ijafri** [comment]
Alright how do i enable wp-svble folder on network sites. I am using sub-directory for network sites. i.e http://abc.com/networkblog

**Comment by rickyrauch** [comment]
Demo is MU setup

**Comment by ijafri** [comment]
but the issue i have - wp-svble does not work on subdirectory network blogs.. is there any hack (.htaccess) to get it working on the networking blogs it only works on main blog.
