### ISSUE TITLE
live preview?

### ISSUE THREAD

**Issue by ijafri** [themeskult/wp-svbtle#104]
isn't 2nd pane in editor supposed to show "live preview" i meant the formatted text appear as you type?

**Comment by ahmetb** [comment]
that would be a good improvement. but making it live won't make you able to see how it looks like on wp-svbtle theme.

**Comment by ijafri** [comment]
well, for that purpose we have preview button already. I was talking about live preview, because not so many people are familiar with markdown syntax, heck, i often get confused between italic and bold tags ;) ---- so live preview at least would give the idea they are using right tag and how might it appear on live site.

**Comment by dasrecht** [comment]
I worked on this live (as in live as you type) mode a bit by making use of https://github.com/evilstreak/markdown-js

**Comment by ijafri** [comment]
@dasrecht I'd appreciate if you could make required changes and send the pull request :)

**Comment by dasrecht** [comment]
@sifarat working on it... pull request will follow
