### ISSUE TITLE
Nested comments are wacky

### ISSUE THREAD

**Issue by jmergy** [themeskult/wp-svbtle#105]
Once you get down into the 3rd level, it get wacky. 

Check it out >> http://mergy.org/2012/12/irecognition-i-am-no-longer-apples-target-market/

The Doc Searls comment. Like 2 words a line...

**Comment by rickyrauch** [comment]
This is already fixed. Please update.

**Comment by jmergy** [comment]
I will check it out. Thank you.

**Comment by jmergy** [comment]
Thank you. Works well now. http://mergy.org
