### ISSUE TITLE
Menu Not Working

### ISSUE THREAD

**Issue by kreativmind** [themeskult/wp-svbtle#109]
I created a menu called Main. I then adding a custom link and one page to the menu. Saved it. Then went to my homepage, but the menu is still the same. I even have Main selected under the section that states my theme only supports 1 menu.

Strange. Any idea?

**Comment by kreativmind** [comment]
Why did you close the ticket instead of answering my question?

**Comment by rickyrauch** [comment]
Sorry, it was a mistake. We don't want to add "more" to the left sidebar. Keep it simple for now.

**Comment by kelso** [comment]
I have the same problem. I need to setup my custom menu.

**Comment by samdoidge** [comment]
Have you selected your new menu under 'Theme locations' within the Menu admin?

I have tested and custom menus should be working.

**Comment by kelso** [comment]
Yes, I did. And nothing happened. I see default menu only.

**Comment by samdoidge** [comment]
It works with a fresh install of WP 3.5.1 and the latest version of wp-svbtle for me:
![Screen shot 2013-04-11 at 16 26 32](https://f.cloud.github.com/assets/845238/368293/4c057e60-a2bc-11e2-86b9-00e0f7cfd74e.png)

**Comment by rickyrauch** [comment]
@samdoidge Thanks for the screenshot :)

**Comment by kelso** [comment]
@samdoidge I'm using this repository https://github.com/webjames/heroku-wordpress-svbtle

Sorry maybe there is an older version of wp-svbtle theme and that's the problem.

**Comment by samdoidge** [comment]
@gravityonmars :)
@kelso Ok, there lies the problem
