### ISSUE TITLE
Unused div when comments are disabled

### ISSUE THREAD

**Issue by Topuz** [themeskult/wp-svbtle#110]
Steps to reproduce:
1. Make a post.
2. Turn off comments.
3. There's an empty div where comments used to be, bordered with two horizontal lines.

![comments](https://f.cloud.github.com/assets/3016596/5774/116b2a28-4396-11e2-9c19-e38c39534118.png)

Something should be done to prevent bottom line or whole comments div from appearing.

**Comment by dasrecht** [comment]
hum... saw that... i guess i can fix this

**Comment by rickyrauch** [comment]
@dasrecht Thank you so much man.
