### ISSUE TITLE
WP 3.5 ?

### ISSUE THREAD

**Issue by jmergy** [themeskult/wp-svbtle#111]
Any takers? Hesitant to upgrade because I don't want to mess with wp-svbtle goodness...

**Comment by dasrecht** [comment]
No worries it works I tested it with Wordpress 3.5 RC5.

/bastian

jmergy notifications@github.com schrieb:

> Any takers? Hesitant to upgrade because I don't want to mess with
> wp-svbtle goodness...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gravityonmars/wp-svbtle/issues/111

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jmergy** [comment]
Sweet!

Thanks. Going to 3.5 now.
