### ISSUE TITLE
Images distorted on mobile site

### ISSUE THREAD

**Issue by edent** [themeskult/wp-svbtle#113]
Small images are unnaturally stretched to be full width if there is no size information in the tag.
Large images are horizontally resized, but stretched vertically.

For example
`<img src="flattr-badge-large.png" alt="flattr this!">`
shows as
![2012-12-14 07 30 28](https://f.cloud.github.com/assets/837136/12922/98c050ec-45d1-11e2-82eb-f82b11d9201d.png)

And
`<img src="anim1.jpg" class="size-full wp-image-358" height="480" width="640">`
![2012-12-14 07 31 32](https://f.cloud.github.com/assets/837136/12921/983e98fe-45d1-11e2-8adf-4ea3e3fc25bd.png)

**Comment by samdoidge** [comment]
adding 

```
height:auto; 
```

to images stop the vertical stretching - have added a pull request.

I was thinking the stretching of images without sizes attributes to 100% was intentional, but do we want this?

**Comment by dasrecht** [comment]
@samdoidge i remember i removed something on my branch about this.. not pushed it... i had some problems with iframes (mostly youtube and vimeo embeds) 

But this was concerning the desktop view and not the mobile one. probably it's ok for others but for for me it wasnt... i'll come up with this

**Comment by samdoidge** [comment]
@dasrecht Ok, let me know if you find the issue. Youtube embeds in Chrome seem fine to me
