### ISSUE TITLE
Wp-Svbtle does not install - style sheet error

### ISSUE THREAD

**Issue by ryanckulp** [themeskult/wp-svbtle#118]
When I upload the Svbtle theme to my WP, says..

"The package could not be installed. The theme is missing the style.css stylesheet."

I see a couple style.css files in the folder hierarchy.. maybe they are misplaced? Maybe a mod needs tweaking for WP 3.5?

Thanks in advance!

**Comment by dasrecht** [comment]
try just to upload the svbtle folder within wp-content/themes ;)

**Comment by ryanckulp** [comment]
I could do that via the filemanager plugin, but it would have to be done 1
file at a time. Zip files won't expand.

Are you suggesting some sort of FTP? I just bought a basic Wordpress
hosting package on Network Solutions, so I'm not sure how easily I could do
that.

Thoughts?

On Wednesday, December 19, 2012, Bastian Widmer wrote:

> try just to upload the svbtle folder within wp-content/themes ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gravityonmars/wp-svbtle/issues/118#issuecomment-11551974.

## 

Ryan Kulp http://www.linkedin.com/in/rkulp2
Author of *Professionalism in Flip Flopshttp://professionalisminflipflops.com
*
678.431.7729

**Comment by dasrecht** [comment]
just download the zip

unpack it

go into wp-content/theme 

zip the folder you see there and upload it.

should work

**Comment by ryanckulp** [comment]
OK, so I did all that. Got the theme activated and every file uploaded to the root, EXCEPT for edit.php, found within wp-svbtle / views. 

Using a file manager plugin to upload each file manually, since my Wordpress hosting package doesn't allow FTP management from Network Solutions. 

Is something corrupted with the edit.php file? File manager won't let me upload it. This is the only file I need to place to make posting work. Otherwise I can log in at domain.com/wp-svbtle.
