### ISSUE TITLE
Privacy settings - not working

### ISSUE THREAD

**Issue by ryanckulp** [themeskult/wp-svbtle#120]
On my privacy settings page, when I click "Allow search engines to index this site" and click "save," the page refreshes and still says "Ask search engines not to index this site." 

Anybody know what's up? Something wrong with a robots file?

**Comment by ryanckulp** [comment]
No answer, eh? Or to my other issue of the edit.php file not being upload-able to my backend via File Manager? Thanks anyway.

**Comment by rickyrauch** [comment]
This is not our end.

**Comment by shahedkhan30** [comment]
What's your website?

**Comment by ryanckulp** [comment]
I think making it more easily compatible with WP 3.5 is absolutely on your end, or I guess you could also provide a couple links to back-scale to another WP release, which could be equally helpful without all the time spent troubleshooting.

**Comment by ryanckulp** [comment]
Website is ryanckulp.com 
1. Can't upload edit.php (using File Manager plugin, since I have a basic Wordpress hosting package that doesn't include FTP access). This prevents me from being able to use the awesome CMS interface. 
2. Privacy settings keep saving as "no index, no follow" and I can't find the Robots script in the header/etc style sheet to remove and override.
