### ISSUE TITLE
wp-svbtle headline and body text fields displaying as invalid (in red)!

### ISSUE THREAD

**Issue by awelfle** [themeskult/wp-svbtle#129]
Hey guys! I love wp-svbtle. I installed the latest commits, though, and, among other bugs, the headline and body text are displaying in red, which apparently happens when it's "invalid". My debugging skills are pretty poor, and I cannot track down the problem. Anyone else having this problem? Any ideas if I'm not doing something right?

![Screen Shot 2013-01-04 at 7 13 58 AM](https://f.cloud.github.com/assets/1836249/43029/b1cfcf7a-5668-11e2-84d1-23bb7a517740.png)
![Screen Shot 2013-01-04 at 7 15 29 AM](https://f.cloud.github.com/assets/1836249/43030/b1d204b6-5668-11e2-877f-bcb191f6b395.png)

**Comment by kalanga** [comment]
I'm seeing the same issue. I just did a fresh install of the theme.

**Comment by rickyrauch** [comment]
Fixed

**Comment by awelfle** [comment]
You're awesome. Thank you!
