### ISSUE TITLE
Add in a more unique, elegant primary fallback font

### ISSUE THREAD

**Issue by ericandrewlewis** [themeskult/wp-svbtle#143]
The first fallback font is Helvetica, which, although a good go-to, makes this theme a little less elegant.

I suggest that we bolt-on a Google web font. Something comparable to Proxima Nova's elegance and general appeal is [Titillium Web](http://www.google.com/webfonts/specimen/Titillium+Web).

**Comment by feliperaul** [comment]
The primary font is proxima nova, but I'm on a mac and I don't have this font, so all text is rendered with Helvetica.

Is this normal ?

**Comment by rickyrauch** [comment]
You should use typekit.

**Comment by ericandrewlewis** [comment]
Proxima Nova is only in the Portfolio plan or higher from TypeKit ($49/year), not a great solution here.
