### ISSUE TITLE
License? Intellectual property? 

### ISSUE THREAD

**Issue by khromov** [themeskult/wp-svbtle#149]
Project README states this is MIT.
style.css file in the theme states it's GPL2.

What is the license?

Furthermore, I have run the css from Svbtle versus the stylesheet from wp-svbtle through a CSS formatter and compared them. They share ~70% of their codebase. It clearly shows wp-svbtle was created by simply taking the Svbtle CSS code rather than from scratch.

The Svbtle theme is not open-sourced. I have a hard time seeing how this is not copyright infringement.

Would appreciate any information regarding this.

**Comment by rickyrauch** [comment]
https://news.ycombinator.com/item?id=4405331

**Comment by khromov** [comment]
@ricardorauch 

Dustin Curtis might have adapted another theme. But it doesn't mean you are free to copy and paste Dustins work into a new theme, give it an incorrect license and redistribute it.

**Comment by dasrecht** [comment]
ricardo in this point khromov is right.

at least we should get the licensing straightened out
