### ISSUE TITLE
Using wpdb when you should be using higher level APIs

### ISSUE THREAD

**Issue by evansolomon** [themeskult/wp-svbtle#15]
In `implement_ajax()` you're doing a raw SQL query (which is insecure by the way, you're not passing your inputs as arguments to `$wpdb->prepare()`).  Instead, you should use `get_post_meta()`.

**Comment by hermpheus** [comment]
I just looked at the code too, nice find. It was using `$wpdb->prepare()` I suppose, but `get_post_meta()` is more maintainable as well. Thanks.

**Comment by evansolomon** [comment]
It was using `prepare()` but you weren't actually passing your inputs as arguments to it, you were just giving it a SQL string so it would never get sanitized.  The unsanitized `$post_id` opened up the query to SQL injection.

**Comment by rickyrauch** [comment]
Fixed :D
