### ISSUE TITLE
Fix comments style

### ISSUE THREAD

**Issue by rickyrauch** [themeskult/wp-svbtle#150]
Comments are broken. How can help me on this?

**Comment by jzone3** [comment]
I looked around in inspect element and here is the reason that the icon is so big:

![Screen Shot 2013-03-29 at 12 09 46 PM](https://f.cloud.github.com/assets/1629612/318079/26619d46-988b-11e2-8299-d68d13b48a0e.png)

**Comment by rickyrauch** [comment]
Thanks man.
