### ISSUE TITLE
Kudos count error

### ISSUE THREAD

**Issue by montogeek** [themeskult/wp-svbtle#152]
In the svbtle dashboard, the kudos count shows a different number than the public website.

**Comment by dasrecht** [comment]
@montogeek : the count on the editor dashboard is the wordcount of the post and not the kudo count.

**Comment by montogeek** [comment]
Oh, thank you! But Why is the wordcount?

**Comment by dasrecht** [comment]
i don't know why exactly... but it would be easy to change ;)

**Comment by montogeek** [comment]
I think is a good reference to know how long are your post directly from the dashboard because the theme is for write, focused in the content. :)

**Comment by samdoidge** [comment]
I did not know what the number referenced either.. changing to kudos count would be an improvement I think

**Comment by samdoidge** [comment]
@montogeek Ok I guess I can see that argument, especially on the unpublished / ideas section

**Comment by montogeek** [comment]
Do you think is better show the Kudos count or the post wordcount?

**Comment by rickyrauch** [comment]
Kudos
