### ISSUE TITLE
[NEW] Sidebar comments per paragraph like at medium.com

### ISSUE THREAD

**Issue by avocade** [themeskult/wp-svbtle#159]
Would be great to have comments to the right of individual paragraphs, making them more contextual and interesting:

https://medium.com/about/5972c72b18f2

**Comment by dasrecht** [comment]
phew :) i guess this one will be hard to archieve with the default behaviour.

but probably we could extend the comment with the paragraph "id"

but what happens if someone adds a paragraph after the users already added some comments?

**Comment by Akamaozu** [comment]
This would be a total departure from Svbtle theme (and Wordpress in general) but it would be a totally welcome change, in my books. Not everyone might agree, so it would be nice to be able to choose what style of comment rendering you'd prefer.

**Comment by avocade** [comment]
Yeah, perhaps this warrants looking a bit closer at the medium source to figure out how they did it. Perhaps giving each `<p>` a unique ID? But what about removing that paragraph later, should it remove the notes too or just move them to a separate place?

Akamazou: Must be configurable (and non-default) of course.

**Comment by Akamaozu** [comment]
Also, what happens when you move a paragraph around or edit it ... what's the best way to correctly track these changes?

**Comment by ihorvorotnov** [comment]
Hey everyone. I was looking for the Medium-like comments solution and found this: https://github.com/pommiegranit/paragraph_commenting

Hope it helps. Testing it right now.

**Comment by kevinweber** [comment]
A very easy-to-use solution for WordPress users is my plugin »Inline Comments«:
www.kevinw.de/inline-comments.
It's available for free on WordPress.org.
