### ISSUE TITLE
How to remove the kudos button?

### ISSUE THREAD

**Issue by almeidamarcell** [themeskult/wp-svbtle#164]
I would really like to remove the kudos button. Anyone has idea how?

**Comment by jmergy** [comment]
I did this for a while, but decided to put it back. Richard gave us the 
heads-up to include this in the style.css

aside.kudo{display:none !important}

An older style.css with the added line is here >>
https://github.com/jmergy/wp-svbtle/blob/mergytweaks/wp-content/themes/svbtle/style.css
(but I did that about 6 months ago so don't use the file, but view it 
to see placement of the above.)

But, I say just keep it.
