### ISSUE TITLE
Editing posts borks if Markdown plugin is already installed

### ISSUE THREAD

**Issue by adityavm** [themeskult/wp-svbtle#2]
Maybe the admin should check if the Markdown plug-in is already installed and just use the installed plug-in if it is?

**Comment by cdevroe** [comment]
@adityavm I quickly forked and patched this issue in this commit: https://github.com/cdevroe/wp-svbtle/commit/896c1ba376ee3c57da394b71db485f316c3ef57c - I've sent a pull request to @gravityonmars too.
