### ISSUE TITLE
Svbtle Dashboard Save Ruining Text

### ISSUE THREAD

**Issue by ghost** [themeskult/wp-svbtle#22]
If I write a post in the Svbtle Dashboard, then click save, it turns a well formated text:
## This is an example

Lorem Ipsum dolor sit amit. Something about this latin crap.
I don't know

Into this:
## This is an example Lorem Ipsum dolor sit amit. Something about this latin crap. I don't know

Publishing it, keeps the formatting, but the saved text is not formated properly, so another save would publish the unformatted text.

**Comment by rickyrauch** [comment]
@norablindsided Can you try the latest version please? I can't reproduce this error.

**Comment by rickyrauch** [comment]
Hey @norablindsided Any update on this? I think I should close this issue.

**Comment by ghost** [comment]
I'm using the most recent version of the project, having the issue in chrome on Mac OS and chrome and Firefox in widows 7

Still jumbling text.

**Comment by rochers** [comment]
I had this problem too but it was because I had pasted the text from a program that was not including the correct line endings so they were not being preserved. Nora, can you try creating a new post, typing that text in manually, and then saving ... does it still happen?
