### ISSUE TITLE
"Start typing idea..." doesn't translate to title

### ISSUE THREAD

**Issue by danawoodman** [themeskult/wp-svbtle#30]
When typing in the "Start typing idea an idea here...":

![](http://f.cl.ly/items/2l1l0d1y2N2M1R0B2K2T/Screen%20shot%202012-07-28%20at%2010.41.42%20AM.png)

![](http://f.cl.ly/items/3G2I3P2F3z1m1V47160y/Screen%20shot%202012-07-28%20at%2010.44.01%20AM.png)

![](http://f.cl.ly/items/3q3O3j2Y3T3I36310c2x/Screen%20shot%202012-07-28%20at%2010.44.29%20AM.png)

and clicking enter does not pre-populate the title with the idea name, which is what I logically assume. 

Not sure if this is a bug or if it is intended (or a problem with my install...)

**Comment by joshkerr** [comment]
I am also experiencing this issue.

**Comment by danawoodman** [comment]
Rock on!

![](http://s3.amazonaws.com/rapgenius/1291131680_two-thumbs-up.jpg)

**Comment by impronunciable** [comment]
haha
