### ISSUE TITLE
Linked titles vs Normal titles

### ISSUE THREAD

**Issue by joshkerr** [themeskult/wp-svbtle#33]
Would love the option to see linked titles (with the anchor icon) that leads you to a specified URL.  This is what Svbtle does.  2 types, normal without link, or link.

**Comment by rickyrauch** [comment]
We already have this implemented on wp-admin/. I have to figure out where this is gonna be on /wp-svbtle

**Comment by rickyrauch** [comment]
Fixed. Please click option on edit page.
