### ISSUE TITLE
Request: search

### ISSUE THREAD

**Issue by joshkerr** [themeskult/wp-svbtle#36]
I know the original SVBTLE doesn't have search, but it would be nice to have the option to include a search box on the page.  Maybe to the right of the date in that white space at the top right side of the page?

**Comment by rickyrauch** [comment]
Let me know what you think

**Comment by joshkerr** [comment]
The search box appears to be aligned a little strange.  Maybe about 10px too far to the right?

This works great though, it was exactly what I needed.
