### ISSUE TITLE
Widgets?

### ISSUE THREAD

**Issue by ghost** [themeskult/wp-svbtle#38]
Can we add widgets to the theme? (Wp says no :( )

Also, to what extend can the left sidebar be customized? :)

Awsome theme guys. Thank you very much for the hard work ^^

**Comment by ghost** [comment]
Also, where do menus appear? 

Cheers.

**Comment by joshkerr** [comment]
+1

**Comment by silent1mezzo** [comment]
+1 Having the left sidebar as a menu is a good idea.

**Comment by rickyrauch** [comment]
Fixed, Feedback?

**Comment by ghost** [comment]
Wait, what did you change? widgets? menu?
Reading the code, it seams you added widgets right?

**Comment by joshkerr** [comment]
Widgets and menu items both work for me.
