### ISSUE TITLE
How to access screenshots content

### ISSUE THREAD

**Issue by ghost** [themeskult/wp-svbtle#39]
Howdy,

How can I access the places shown in:
- https://github.com/gravityonmars/wp-svbtle/raw/master/wp-svbtle/screenshot-2.png
- https://github.com/gravityonmars/wp-svbtle/raw/master/wp-svbtle/screenshot-1.png

Thank you.

**Comment by rickyrauch** [comment]
http://yoursite.com/wp-svbtle

**Comment by ghost** [comment]
Awsome! ty.
