### ISSUE TITLE
Font option for composing posts

### ISSUE THREAD

**Issue by joshkerr** [themeskult/wp-svbtle#41]
I'd love to see an option to change the writing font in the WP-SVBTLE admin area.  Support for adding your own javascript (typekit) would be great too.

**Comment by pixelyunicorn** [comment]
:+1:

**Comment by rickyrauch** [comment]
Do you mean your own js on each post?

**Comment by joshkerr** [comment]
No, not for posts, but for the wp-svbtle admin area.  Since that admin doesn't leverage wordpress plugins, we can't choose additional fonts.  Allowing us to insert our own javascript would allow us to use external fonts from Google and Typekit.

**Comment by rickyrauch** [comment]
I think we are going to keep all the technical stuff on wp-admin. Thanks again for your feedback it helps a lot.
