### ISSUE TITLE
Post Titles: Regular Post vs. External Link

### ISSUE THREAD

**Issue by ericleamen** [themeskult/wp-svbtle#42]
All post titles are now formatted as external links. 

Regular post titles with no external link should be formatted like this:
http://dl.dropbox.com/u/3532230/WP-Svbtle-NoLink.png

And post titles with an external link should be formatted like this: 
http://dl.dropbox.com/u/3532230/WP-Svbtle-ExternalLink.png

**Comment by rickyrauch** [comment]
Can you please take the latest version please?
