### ISSUE TITLE
Unicode encoding problem in posting

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#45]
In svbtle-like posting interface (/wp-svbtle) if I write something using unicode characters (e.g. in my case some accents from Turkish alphabet) into post title box, they are saved wrong.

For instance if you specify title as `Ürün anlayışı` it is converted to `Ã¼rÃ¼n anlayÄ±Å`. Content field does not have this problem, it's only the title.

**Comment by ahmetb** [comment]
Solved. Please fix `process_post.php` line 125 as follows:

Replace `$post_title = htmlentities($post_title);` with

```
$post_title = htmlentities($post_title, ENT_QUOTES, 'UTF-8');
```

This will prevent problems in non-English blogs. Thanks.

**Comment by rickyrauch** [comment]
@ahmetalpbalkan 
NICEEEENICEEEENICEEEENICEEEENICEEEENICEEEENICEEEENICEEEENICEEEENICEEEENICEEEE
