### ISSUE TITLE
strip_tags for word count in svbtle dashboard

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#46]
As far as I observed HTML tags are considered as words and shown in that circles on wp-svbtle dashboard.

e.g. `<iframe width="500" height="281" src="https://www.youtube.com/embed/UvEiSa6_EPA?rel=0" frameborder="0" allowfullscreen></iframe>` this is considered 15 words. If you would use [`strip_tags`](http://php.net/manual/en/function.strip-tags.php), it will throw away what's between `<` & `>` .

It should be fixed at https://github.com/gravityonmars/wp-svbtle/blob/master/wp-svbtle/views/dashboard.php#L41 . I'd appreciate if you can spare some time on this. Thanks!

**Comment by rickyrauch** [comment]
@ahmetalpbalkan Thanks for your help!!!!

**Comment by ahmetb** [comment]
cool job, you're welcome!
