### ISSUE TITLE
Name doesn't display under header

### ISSUE THREAD

**Issue by ericleamen** [themeskult/wp-svbtle#54]
Sorry to bother guys. I just installed the latest version of WP-SVBTLE, but my full name isn't displaying under the header like it should. Any idea what I am doing wrong or how I can fix it? Thanks! http://ericleamen.com

**Comment by rickyrauch** [comment]
Please add first name and last name on your profile.

**Comment by ericleamen** [comment]
I did that, and it still isn't showing up for some reason.
