### ISSUE TITLE
wp-svbtle in root shows a 404

### ISSUE THREAD

**Issue by blaireaug** [themeskult/wp-svbtle#6]
I've installed the directory where I'm supposed to, yet when I go to mysite.com/wp-svtble, it's a 404. I'm not sure what I'm missing here. Would it being a multi-user wp install have anything to do with this?

**Comment by blaireaug** [comment]
More details.

I've now tried it on 2 wp installations. When not logged in, going to site.com/wp-svtble will redirect to wp-login, which then redirects to original wp-dashboard.

When logged in, visiting /wp-svbtle/, redirects to /wp-svbtle/?page=dashboard, which is a 404.

Sometimes, it returns that the nocache_headers is an undefined function.

I'm not sure where it's going wrong.

**Comment by adrianherritt** [comment]
I'm having the same issue - a 404 at /wp-svbtle/?page=dashboard. Can anyone else verify a successful install from the files here? Ricardo, any suggestions? Thanks!

**Comment by rickyrauch** [comment]
Hey Guys, I removed one file: .htaccess. Can you please update to the latest version? 

In case it doesn't work, please paste error_log's output.

Thanks!

**Comment by rickyrauch** [comment]
@adrianherritt my gtalk is ricardo@gravityonmars.com

**Comment by blaireaug** [comment]
Okay, so I've updated. I'm able to run the Svbtle dashboard on a local server. But the one on my shared hosting can't run it. Are there any dependencies other than having a wordpress install?

Hmmm. Maybe this helps?

[20:40:51.873] GET http://www.site.com/wp-svbtle/?page=dashboard [HTTP/1.1 404 Not Found 913ms]
[20:41:01.299] GET http://www.site.com/wp-svbtle/ [HTTP/1.1 302 Found 1253ms]
[20:41:02.559] GET http://www.site.com/wp-svbtle/?page=dashboard [HTTP/1.1 404 Not Found 1103ms]

**Comment by rickyrauch** [comment]
@adrianherritt @blaireaug Can you please try the new version? Thanks

**Comment by adrianherritt** [comment]
Just tried. Still getting a 404 on wp-svbtle/index.php?page=dashboard

**Comment by jerzygangi** [comment]
I'm receiving a 404 error, too. If I can help just let me know what log files, etc. to check and I'll show you what precise errors I'm getting.

**Comment by rickyrauch** [comment]
@jerzygangi Yes, please send me the logs.
