### ISSUE TITLE
error for child themes in functions.php

### ISSUE THREAD

**Issue by jshwlkr** [themeskult/wp-svbtle#61]
Line 237in functions.php, which reads:

``` php
require_once ( get_stylesheet_directory() . '/theme-options.php' );
```

causes a 500 error when creating a child theme if you do not have a theme-options.php file in your child directory.

**Comment by rickyrauch** [comment]
@jshwlkr I don't get it, What do you mean by child theme?

**Comment by jshwlkr** [comment]
Trying to do this-- http://codex.wordpress.org/Child_Themes causes a 500 error unless you also create a theme-options file.

**Comment by jeffwidman** [comment]
@jshwlkr Is this still an open issue? 

I'm about to start creating a child theme myself.

**Comment by jshwlkr** [comment]
I'm not sure, I think so since I don't believe the functions.php has been changed.

**Comment by jeffwidman** [comment]
Hmm. I just created a child theme and it showed up okay without them-options.php file, not hitting the 500 error you saw
