### ISSUE TITLE
Long articles do not scroll properly in post editor

### ISSUE THREAD

**Issue by joshkerr** [themeskult/wp-svbtle#63]
Take a long article, put it in the svbtle post editor.  Now try to edit the bottom of the article.  You'll see that it scrolls out of view and you can't see what you are typing.

**Comment by joshkerr** [comment]
Backspace key causes entire editor to scroll to the top.  (When article content flows beyond the bottom of the page.)

**Comment by rickyrauch** [comment]
Browser?

**Comment by joshkerr** [comment]
Chrome

**Comment by sarcastillo** [comment]
I can confirm this behavior on Chrome Canary as well. Long article, press backspace (or delete in my case), the entire article scrolls back to the top.
