### ISSUE TITLE
Still hardcoded links to someone else's cloudfront CDN in style.css

### ISSUE THREAD

**Issue by joshkerr** [themeskult/wp-svbtle#66]
You need to remove this.  I'm getting so much traffic that I'm actually going to rack up a bill for this unlucky person.

Search "cloudfront" and "mysterious" to find the hardcoded links.

**Comment by rickyrauch** [comment]
Yup, but all of them are overwritten.

**Comment by joshkerr** [comment]
Still shows on my live site.

**Comment by jamesonjlee** [comment]
for one of the images it's already fixed in line 13.
I suggest adding the similar below to handle the other 2.

```
aside.kudo.complete span.circle{background-image:url("images/bolt_large.png");}
aside#logo div a{background:#000 url("images/bolt_large.png") center center no-repeat;}
```
