### ISSUE TITLE
Negative kudos

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#69]
I was looking at `remove_kudos` function in `functions.php` and I could not see any checks that prevent kudos from being negative. 

An abuser may repeat `remove_kudos` request by clearing cookies in between the requests and it will result in negative kudos.

So maybe you can do something like `if ($new_kudos < 0) $new_kudos = 0`. Thanks.

**Comment by rickyrauch** [comment]
@ahmetalpbalkan good point
