### ISSUE TITLE
Markdown does not support code blocks

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#75]
Encapsulating multiple lines of code inside  ``` (three of'em) characters does not work. First two backticks are converted to " (quote mark) therefore it does not work. Any workaround?

**Comment by ahmetb** [comment]
You can see how a code block looks like on svbtle blogs in this post: http://byfat.xxx/if-hemingway-wrote-javascript

Btw I found my way around `<pre><code class='js'></code></pre>`

**Comment by rickyrauch** [comment]
This is fixed by using Pretify.js

**Comment by ahmetb** [comment]
Great thanks.
