### ISSUE TITLE
Redirection to home upon 404 and showing message

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#76]
I saw what wp-svbtle implemented on 404 page and the search idea is quite convenient, but as svbtle changes, new minmalistic features come in.

Upon a 404 error on the blogs, svbtle takes users to the homepage and shows a message: 

![Svbtle 404](http://i.imgur.com/TAKju.png)

**Comment by rickyrauch** [comment]
Done by @ahmetalpbalkan
