### ISSUE TITLE
My 300*300px logo does not fit inside anymore

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#80]
Which commit might have caused this?  It used to fit very great inside that circle. dcurt.is website has a 500*500px logo and it fits and aligns the middle. For diagnostics: [[link]](http://ahmetalpbalkan.com/blog/)

![](http://i.imgur.com/6Vvjj.png)

EDIT-1: Apparently this happens on Chrome, neither OS X Safari nor iOS Safari could reproduce this.
EDIT-2: Using browsershots.org I have seen that this is broken on Chrome 21 on Debian, Chrome 23 on Windows but works fine on Chrome 18 on Windows. How weird...

**Comment by ahmetb** [comment]
Found it! https://github.com/ahmetalpbalkan/wp-svbtle/commit/9048a0ba0fae8bead53b09b2d2f46b94f8909816#L2R14

You added a line with bolt image and it appeared enlarged in that small circle.

**Comment by rickyrauch** [comment]
Fixed.

**Comment by ahmetb** [comment]
Thanks!
