### ISSUE TITLE
Are you collecting information about our blogs?!

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#82]
I have just seen the following code in my footer

```
<img src='http://gravityonmars.com/wp-svbtle.php?host=http://ahmetalpbalkan.com/blog&name=%2Fhome%2Falp&icon=http%3A%2F%2Fahmetalpbalkan.com%2Fblog%2Fwp-content%2Fuploads%2F2012%2F09%2Fcloud1.png&color=%23f1223b' />
```

**Why the hell do you do that?** This just conflicts with the open source philosophy. Why do you have all my analytics data (user demographics, country info, IP addresses etc.) I am so irritated. Is this why we see all commit messages as  just `fixes`?

**Comment by rickyrauch** [comment]
Remove it.

**Comment by ahmetb** [comment]
I removed it but you SHOULD explain what kind of data you are collecting about people. This is very ugly.

**Comment by rickyrauch** [comment]
We are trying to build a community. Users and contributors. 
Anyway I've removed that pixel that only was shown for admins.

**Comment by ahmetb** [comment]
Why not put this as an option to Admin Panel (which may be enabled by default). If you create a mail subscription list for wp-svbtle project updates I'd love to subscribe, at least you should describe purpose of that image inside  comment and this way people would be less scared.

**Comment by rickyrauch** [comment]
Can you do it for me?

**Comment by ahmetb** [comment]
In the last commit I observed you removed related part from `functions.php`. This idea is a little bit dangerous, if you put such an option, it would be good for your plans for creating community but assume wp-svbtle is used by a company for internal (and thus confidential) communication, then wouldn't be the contents (or title) of the confidential story be leaked out?
