### ISSUE TITLE
Can this be installed as a plugin?

### ISSUE THREAD

**Issue by RaphiePS** [themeskult/wp-svbtle#87]
I'm using a Wordpress host that makes you pay $25 for SFTP access, so I'm interested in getting this working with no access to the file system. I've already installed the theme, but can the editor be installed as a plugin somehow?

**Comment by Coopeh** [comment]
What about something like http://wordpress.org/extend/plugins/wp-filemanager/?

**Comment by RaphiePS** [comment]
I tried that, but it doesn't support zips. While uploading the 15 or so files one at a time is certainly worth the $25 savings for me, I'm just wondering if there's an easier way.
