### ISSUE TITLE
Header Color Error

### ISSUE THREAD

**Issue by JeffBajayo** [themeskult/wp-svbtle#9]
Get browser error when changing header color. looks like this. 

Warning: array_key_exists() [function.array-key-exists]: The second argument should be either an array or an object in /home/jeff/public_html/blog/wp-content/themes/svbtle/theme-options.php on line 73

Warning: Cannot modify header information - headers already sent by (output started at /home/jeff/public_html/blog/wp-content/themes/svbtle/theme-options.php:73) in /home/jeff/public_html/blog/wp-includes/pluggable.php on line 866

**Comment by rickyrauch** [comment]
Closed as resolved.
