### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by jonathanhadams** [themeskult/wp-svbtle#90]
Kudos don't show comma after 1,000

**Comment by jmergy** [comment]
I can't get any kudos to stick. Any ideas?

**Comment by jmergy** [comment]
site >> http://mergy.org

**Comment by rickyrauch** [comment]
@jmergy Doesn't work for the moment with any cache plugin.

**Comment by jmergy** [comment]
Thanks. Huh, I disabled all the plugins except for 4 now and still playing with it. These are my active plugins 

SI CAPTCHA Anti-Spam
Stream Video Player
TinyMCE Advanced
Twitter Image Host

Anyway, I really like Symbol so might just move over to that. 

http://symbol.themeskult.com/

**Comment by rickyrauch** [comment]
@jmergy Your issue was related to #84.

Nice theme ;)

**Comment by jmergy** [comment]
Can't seem to find the best way to disable kudos in the code. I just played the latest code and can go in and mess with it to disable it, but what is the recommended way? Could this eventually be an option to flip on or off?

**Comment by jmergy** [comment]
Found the email on this. All good. 

---

Open style.css and add this line at the bottom:

aside.kudo{display:none !important}
