### ISSUE TITLE
Figure out how date on home page works on Svbtle

### ISSUE THREAD

**Issue by ahmetb** [themeskult/wp-svbtle#93]
When I go to http://dcurt.is/ homepage, the header shows Oct 07, 2012 as date (where wp-svbtle shows today's date). When I click the latest post on homepage, now it shoows Oct 03, 2012. (and today is Oct 23, 2012) What could be the logic behind this?

**Comment by hdmn** [comment]
i dont think this is on purpose. whether a cloudfront caching problem…

**Comment by ahmetb** [comment]
Yes that actually could be wrong. When I hit refresh, kudos count for latest post is loaded as 1027 and then after DOM is ready, it is changed to actual value. Thanks for the heads up.
