### ISSUE TITLE
Feature Req: Readers upvote future post topics (drafts)

### ISSUE THREAD

**Issue by cballou** [themeskult/wp-svbtle#94]
I've had this idea kicking around since the launch of svbtle. What if you were to add a sidebar containing all of your draft posts with a vote feature to gauge reader interest in upcoming topics? My initial thought was that it would drive more traffic if you're writing about things they want to hear and can scrap the stuff they don't.

I was going to build it myself, but you've already put some effort into this project so it might make sense to either offer it directly or simply create a svbtle recommendation sidebar widget as a drop-in.

What do you think?

**Comment by ahmetb** [comment]
I am not sure we should go ahead of Svbtle, because this is not the aim of the project I think. However if they go for it and it looks good, we can easily follow. But for now, IMO, it violates minimalist approach.

**Comment by rickyrauch** [comment]
Yes, this goes against the rules. Thanks for your feedback anyway.
