### ISSUE TITLE
Categories?

### ISSUE THREAD

**Issue by tobsterz58** [themeskult/wp-svbtle#95]
Hi there, 

I love the theme! But as a blogger, I'd really, really like the ability to add a categories widget so that users can sort blog posts. Right now, the only options for searching anything is the search bar or scrolling, but if you have hundreds of posts, it can get tiresome for a user to scroll indefinitely or think of search terms to plug in. Consider a categories widget maybe?

**Comment by loop** [comment]
This theme is based on Svble so I don't see the point of adding features which don't exist on the original. But seeing as this is released under MIT License, I don't see why you cannot fork it and add the category hooks to the code. If I have time I will do it under my fork but I don't think this is a good idea yet.
