### ISSUE TITLE
Images stretched

### ISSUE THREAD

**Issue by jwmoss** [themeskult/wp-svbtle#96]
When I add images using MarsEdit (written in rich text), on iOS it stretches out the image:

https://www.dropbox.com/s/ixrz75n2rky1lo4/Photo%20Nov%2005%2C%202%2019%2048%20PM.png

Any way to fix this or am I missing something when posting to wp-svbtle from MarsEdit/other blogging clients?

**Comment by ahmetb** [comment]
It has nothing to do with MarsEdit. It is a css property that comes with the theme. It works the same way in original Svbtle but I also agree that's not something good. Remember, Svbtle is designed mostly for essay-writing blogs. Not any technical writing etc.

**Comment by jwmoss** [comment]
So, best practice for managing/uploading content is by editing CSS each time? Which part of the code handles it?

**Comment by rickyrauch** [comment]
I think we are going to set height: auto. This rule sucks.
